ignore:
  - "src/main/java/com/mikkezavala/sat/domain/**/*"
  - "src/main/java/com/mikkezavala/sat/configuration/**/*"

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 1%