ignore:
  - "src/main/java/com/mikkezavala/sat/domain/**/*"
  - "src/main/java/com/mikkezavala/sat/configuration/**/*"
<<<<<<< HEAD

coverage:
  precision: 2
  round: down
  range: "65...100"
=======
coverage:
  status:
    project:
      default:
        threshold: 70%
<<<<<<< HEAD
>>>>>>> 25f43cd (codecov thrshold)
=======
>>>>>>> ec0be6e (whitespace)
