version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -U -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload:
          flags: '540e7216-8400-4371-bc12-0ab6ebd10409'
          file: target/reports/jacoco.xml
workflows:
  build:
    jobs:
      - build-and-test
